### ISSUE TITLE
Option regex not matching one specific case

### ISSUE THREAD

**Issue by sthiago** [ebemunk/node-uci#23]
Hello, there.

When initializing Rodent IV (http://www.pkoziol.cal24.pl/rodent/rodent.htm), one of the options is Personality and the default value is three dashes (---). The regex at https://github.com/ebemunk/node-uci/blob/master/src/const.js#L7 fails to match that case (https://regex101.com/r/PBZlYk/1/). Adding a dash to the list of values to that match group solves the problem. 

Btw, I was left wondering why the matching expression for the default value is a lot more complex than the others. Could it be the same as the `var` one `(.+)` or would it cause problems with other engines?

**Comment by ebemunk** [comment]
Thanks for finding this issue! `---` or any `-` value I haven't seen before, but I suppose it's not a deal breaker as far as the UCI standard is concerned. I don't see anything in the UCI text that prohibits dashes (or all dashes) for a value. Probably just missed it as it's not common (maybe `None` is a better descriptor in this case than `---` but still).

One reason for why the default is more complicated is because `.+` does a greedy match so I can't capture the following commands in the same line without changing how things are parsed.

For example:
`option name Hash type spin default 16 min 1 max 16384` results in
```
Full match | option name Hash type spin default 16 min 1 max 16384
Group 1. | Hash
Group 2. | spin
Group 3. | 16
Group 4. | 1
Group 5. | 16384
```
changing the capture regex for `default` to be `.+` results in
```
Full match | option name Hash type spin default 16 min 1 max 16384
Group 1. |	Hash
Group 2. |	spin
Group 3. |	16 min 1 max 16384
```
so you can see we miss parsing the `min` `max` and possibly others because of the greedy `.+`.

I don't see any issue in adding `-` to the allowed characters for the `default`. If you want to get a PR for it I will be happy to accept. If not, I will get around to adding it at some point.

**Comment by sthiago** [comment]
Ah, yes, makes total sense. And sure, I'll make a PR. Just a moment

**Comment by ebemunk** [comment]
live now on version 1.3.4

thanks for contributing!
